### ISSUE TITLE
pubsub/gcppubsub: test flaked on Travis

### ISSUE THREAD

**Issue by vangent** [google/go-cloud#1168]
```
?   	gocloud.dev/pubsub/drivertest	[no test files]
SIGQUIT: quit
PC=0x489e21 m=0 sigcode=0
goroutine 0 [idle]:
runtime.futex(0x2249840, 0x80, 0x0, 0x0, 0x7fff00000000, 0x0, 0x0, 0x0, 0x7fff93562a40, 0x433e92, ...)
	/home/travis/.gimme/versions/go1.11.4.linux.amd64/src/runtime/sys_linux_amd64.s:531 +0x21
runtime.futexsleep(0x2249840, 0x7fff00000000, 0xffffffffffffffff)
	/home/travis/.gimme/versions/go1.11.4.linux.amd64/src/runtime/os_linux.go:46 +0x4b
runtime.notesleep(0x2249840)
	/home/travis/.gimme/versions/go1.11.4.linux.amd64/src/runtime/lock_futex.go:151 +0xa2
runtime.stopm()
	/home/travis/.gimme/versions/go1.11.4.linux.amd64/src/runtime/proc.go:2016 +0xe3
runtime.findrunnable(0xc00004c000, 0x0)
	/home/travis/.gimme/versions/go1.11.4.linux.amd64/src/runtime/proc.go:2487 +0x4dc
runtime.schedule()
	/home/travis/.gimme/versions/go1.11.4.linux.amd64/src/runtime/proc.go:2613 +0x13a
runtime.park_m(0xc000001b00)
	/home/travis/.gimme/versions/go1.11.4.linux.amd64/src/runtime/proc.go:2676 +0xae
runtime.mcall(0x0)
	/home/travis/.gimme/versions/go1.11.4.linux.amd64/src/runtime/asm_amd64.s:299 +0x5b
goroutine 1 [chan receive, 9 minutes]:
testing.(*T).Run(0xc00034a100, 0x1610bb5, 0xf, 0x1651e60, 0xc000253bb0)
	/home/travis/.gimme/versions/go1.11.4.linux.amd64/src/testing/testing.go:879 +0x692
testing.runTests.func1(0xc00034a100)
	/home/travis/.gimme/versions/go1.11.4.linux.amd64/src/testing/testing.go:1119 +0xa9
testing.tRunner(0xc00034a100, 0xc000253d20)
	/home/travis/.gimme/versions/go1.11.4.linux.amd64/src/testing/testing.go:827 +0x163
testing.runTests(0xc000340360, 0x222f9c0, 0x1, 0x1, 0x240)
	/home/travis/.gimme/versions/go1.11.4.linux.amd64/src/testing/testing.go:1117 +0x4ef
testing.(*M).Run(0xc000350080, 0x0)
	/home/travis/.gimme/versions/go1.11.4.linux.amd64/src/testing/testing.go:1034 +0x2ef
main.main()
	_testmain.go:526 +0x343
goroutine 6 [select]:
go.opencensus.io/stats/view.(*worker).start(0xc000084ac0)
	/home/travis/gopath/pkg/mod/go.opencensus.io@v0.18.1-0.20181204023538-aab39bd6a98b/stats/view/worker.go:152 +0x1b3
created by go.opencensus.io/stats/view.init.0
	/home/travis/gopath/pkg/mod/go.opencensus.io@v0.18.1-0.20181204023538-aab39bd6a98b/stats/view/worker.go:29 +0x9a
goroutine 108 [select]:
google.golang.org/grpc.(*ClientConn).WaitForStateChange(0xc000298f00, 0x182cea0, 0xc0000341b0, 0x3, 0xc0000d4f01)
	/home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.17.0/clientconn.go:417 +0x15b
google.golang.org/grpc.DialContext(0x182cea0, 0xc0000341b0, 0xc00032b640, 0xf, 0xc000490240, 0x5, 0x6, 0x0, 0x0, 0x0)
	/home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.17.0/clientconn.go:316 +0x1075
gocloud.dev/internal/testing/setup.NewGCPgRPCConn(0x182cea0, 0xc0000341b0, 0xc000120800, 0xc00032b640, 0xf, 0x160863c, 0x6, 0xc000440670, 0x4736ad)
	/home/travis/gopath/src/gocloud.dev/internal/testing/setup/setup.go:149 +0x5ca
gocloud.dev/pubsub/gcppubsub.newHarness(0x182cea0, 0xc0000341b0, 0xc000120800, 0x19d34e0, 0xf, 0x21cb347, 0x48)
	/home/travis/gopath/src/gocloud.dev/pubsub/gcppubsub/gcppubsub_test.go:60 +0x95
gocloud.dev/pubsub/drivertest.testAs(0xc000120800, 0x1651e68, 0x182b0e0, 0x22666d0)
	/home/travis/gopath/src/gocloud.dev/pubsub/drivertest/drivertest.go:375 +0xa4
gocloud.dev/pubsub/drivertest.RunConformanceTests.func8.1(0xc000120800)
	/home/travis/gopath/src/gocloud.dev/pubsub/drivertest/drivertest.go:126 +0x9f
testing.tRunner(0xc000120800, 0xc0004b6720)
	/home/travis/.gimme/versions/go1.11.4.linux.amd64/src/testing/testing.go:827 +0x163
created by testing.(*T).Run
	/home/travis/.gimme/versions/go1.11.4.linux.amd64/src/testing/testing.go:878 +0x65a
goroutine 18 [syscall, 9 minutes]:
os/signal.signal_recv(0x487ae1)
	/home/travis/.gimme/versions/go1.11.4.linux.amd64/src/runtime/sigqueue.go:139 +0x9c
os/signal.loop()
	/home/travis/.gimme/versions/go1.11.4.linux.amd64/src/os/signal/signal_unix.go:23 +0x30
created by os/signal.init.0
	/home/travis/.gimme/versions/go1.11.4.linux.amd64/src/os/signal/signal_unix.go:29 +0x4f
goroutine 19 [chan receive, 9 minutes]:
testing.(*T).Run(0xc00034a200, 0x1607cd0, 0x6, 0xc0004b0ae0, 0x2)
	/home/travis/.gimme/versions/go1.11.4.linux.amd64/src/testing/testing.go:879 +0x692
gocloud.dev/pubsub/drivertest.RunConformanceTests(0xc00034a200, 0x1651e68, 0xc00033a310, 0x2, 0x2)
	/home/travis/gopath/src/gocloud.dev/pubsub/drivertest/drivertest.go:120 +0x6a1
gocloud.dev/pubsub/gcppubsub.TestConformance(0xc00034a200)
	/home/travis/gopath/src/gocloud.dev/pubsub/gcppubsub/gcppubsub_test.go:123 +0xa6
testing.tRunner(0xc00034a200, 0x1651e60)
	/home/travis/.gimme/versions/go1.11.4.linux.amd64/src/testing/testing.go:827 +0x163
created by testing.(*T).Run
	/home/travis/.gimme/versions/go1.11.4.linux.amd64/src/testing/testing.go:878 +0x65a
goroutine 107 [chan receive, 9 minutes]:
testing.(*T).Run(0xc000120700, 0x160a821, 0x8, 0xc0004b6720, 0x18c92f0d)
	/home/travis/.gimme/versions/go1.11.4.linux.amd64/src/testing/testing.go:879 +0x692
gocloud.dev/pubsub/drivertest.RunConformanceTests.func8(0xc000120700)
	/home/travis/gopath/src/gocloud.dev/pubsub/drivertest/drivertest.go:125 +0x26e
testing.tRunner(0xc000120700, 0xc0004b0ae0)
	/home/travis/.gimme/versions/go1.11.4.linux.amd64/src/testing/testing.go:827 +0x163
created by testing.(*T).Run
	/home/travis/.gimme/versions/go1.11.4.linux.amd64/src/testing/testing.go:878 +0x65a
goroutine 109 [select]:
google.golang.org/grpc.(*ccBalancerWrapper).watcher(0xc0004d2800)
	/home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.17.0/balancer_conn_wrappers.go:122 +0x1fd
created by google.golang.org/grpc.newCCBalancerWrapper
	/home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.17.0/balancer_conn_wrappers.go:113 +0x292
goroutine 110 [select]:
google.golang.org/grpc.(*addrConn).nextAddr(0xc000422dc0, 0x181f880, 0xc0004b28b0)
	/home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.17.0/clientconn.go:1338 +0x516
google.golang.org/grpc.(*addrConn).resetTransport(0xc000422dc0, 0x0)
	/home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.17.0/clientconn.go:1008 +0x265
created by google.golang.org/grpc.(*addrConn).connect
	/home/travis/gopath/pkg/mod/google.golang.org/grpc@v1.17.0/clientconn.go:687 +0x18f
rax    0xca
rbx    0x2249700
rcx    0x489e23
rdx    0x0
rdi    0x2249840
rsi    0x80
rbp    0x7fff93562a08
rsp    0x7fff935629c0
r8     0x0
r9     0x0
r10    0x0
r11    0x286
r12    0x1
r13    0x1
r14    0x2
r15    0xc000042360
rip    0x489e21
rflags 0x286
cs     0x33
fs     0x0
gs     0x0
*** Test killed with quit: ran too long (10m0s).
FAIL	gocloud.dev/pubsub/gcppubsub	600.006s
```

**Comment by ijt** [comment]
Has this flake happened again?

**Comment by vangent** [comment]
I haven't noticed it.

**Comment by ijt** [comment]
Okay, I think we can close this out then.
