### ISSUE TITLE
internal/docstore/mongodocstore: panic during conformance test

### ISSUE THREAD

**Issue by vangent** [google/go-cloud#2249]
Got this failure on Travis:

```
=== RUN   TestConformance/Create
panic: reflect: call of reflect.Value.Bytes on array Value
	panic: reflect: call of reflect.Value.Bytes on array Value [recovered]
	panic: reflect: call of reflect.Value.Bytes on array Value
goroutine 16 [running]:
testing.tRunner.func1(0xc00012c400)
	/home/travis/.gimme/versions/go1.12.5.linux.amd64/src/testing/testing.go:830 +0x69d
panic(0x1ed94c0, 0xc00000fb40)
	/home/travis/.gimme/versions/go1.12.5.linux.amd64/src/runtime/panic.go:522 +0x1b5
reflect.flag.mustBe(0x91, 0x17)
	/home/travis/.gimme/versions/go1.12.5.linux.amd64/src/reflect/value.go:207 +0xee
reflect.Value.Bytes(0x1fc9360, 0xc000044800, 0x91, 0x2834fc0, 0x1fc9360, 0x1cc4acc)
	/home/travis/.gimme/versions/go1.12.5.linux.amd64/src/reflect/value.go:260 +0x46
gocloud.dev/internal/docstore/driver.encodeList(0x1fc9360, 0xc000044800, 0x91, 0x2826c20, 0xc00000fb20, 0x0, 0x0)
	/home/travis/gopath/src/gocloud.dev/internal/docstore/driver/codec.go:206 +0x2d3
gocloud.dev/internal/docstore/driver.encode(0x1fc9360, 0xc000044800, 0x91, 0x2826c20, 0xc00000fb20, 0x20, 0x1fa6900)
	/home/travis/gopath/src/gocloud.dev/internal/docstore/driver/codec.go:173 +0xd7a
gocloud.dev/internal/docstore/driver.Encode(0x1fc9360, 0xc000044800, 0x91, 0x2826c20, 0xc00000fb20, 0x0, 0x0)
	/home/travis/gopath/src/gocloud.dev/internal/docstore/driver/codec.go:115 +0x7d
gocloud.dev/internal/docstore/mongodocstore.encodeValue(0x1fc9360, 0xc000044800, 0xc0001446c0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/gocloud.dev/internal/docstore/mongodocstore/codec.go:44 +0xe5
gocloud.dev/internal/docstore/mongodocstore.(*collection).Key(0xc000094c80, 0x1ebb680, 0xc0001446c0, 0xc0001446c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/travis/gopath/src/gocloud.dev/internal/docstore/mongodocstore/mongo.go:219 +0x34c
gocloud.dev/internal/docstore.(*Collection).toDriverAction(0xc0003a1c80, 0xc000095280, 0x6, 0x0, 0x1)
	/home/travis/gopath/src/gocloud.dev/internal/docstore/docstore.go:334 +0x1b9
gocloud.dev/internal/docstore.(*ActionList).toDriverActions(0xc0002d1240, 0xc000000001, 0x5, 0xc00005ae90, 0x29e3b80, 0x2)
	/home/travis/gopath/src/gocloud.dev/internal/docstore/docstore.go:303 +0x1e1
gocloud.dev/internal/docstore.(*ActionList).Do(0xc0002d1240, 0x2801880, 0xc0000be010, 0xc0002d1240, 0x203000)
	/home/travis/gopath/src/gocloud.dev/internal/docstore/docstore.go:275 +0x69
gocloud.dev/internal/docstore/drivertest.testCreate.func1(0xc0003a1c80, 0xc0001443c0, 0xc0001446c0, 0x2801880, 0xc0000be010)
	/home/travis/gopath/src/gocloud.dev/internal/docstore/drivertest/drivertest.go:226 +0x100
panic(0x1ed94c0, 0xc00000fae0)
	/home/travis/.gimme/versions/go1.12.5.linux.amd64/src/runtime/panic.go:522 +0x1b5
reflect.flag.mustBe(0x91, 0x17)
	/home/travis/.gimme/versions/go1.12.5.linux.amd64/src/reflect/value.go:207 +0xee
reflect.Value.Bytes(0x1fc9360, 0xc000044800, 0x91, 0x2834fc0, 0x1fc9360, 0x1cc4acc)
	/home/travis/.gimme/versions/go1.12.5.linux.amd64/src/reflect/value.go:260 +0x46
gocloud.dev/internal/docstore/driver.encodeList(0x1fc9360, 0xc000044800, 0x91, 0x2826c20, 0xc00000fac0, 0x0, 0x0)
	/home/travis/gopath/src/gocloud.dev/internal/docstore/driver/codec.go:206 +0x2d3
gocloud.dev/internal/docstore/driver.encode(0x1fc9360, 0xc000044800, 0x91, 0x2826c20, 0xc00000fac0, 0x20, 0x1fa6900)
	/home/travis/gopath/src/gocloud.dev/internal/docstore/driver/codec.go:173 +0xd7a
gocloud.dev/internal/docstore/driver.Encode(0x1fc9360, 0xc000044800, 0x91, 0x2826c20, 0xc00000fac0, 0x38e13e0, 0x97)
	/home/travis/gopath/src/gocloud.dev/internal/docstore/driver/codec.go:115 +0x7d
gocloud.dev/internal/docstore/mongodocstore.encodeValue(0x1fc9360, 0xc000044800, 0xc00039e060, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/gocloud.dev/internal/docstore/mongodocstore/codec.go:44 +0xe5
gocloud.dev/internal/docstore/mongodocstore.(*collection).Key(0xc000094c80, 0x1ebb680, 0xc00039e060, 0xc00039e060, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/travis/gopath/src/gocloud.dev/internal/docstore/mongodocstore/mongo.go:219 +0x34c
gocloud.dev/internal/docstore.(*Collection).toDriverAction(0xc0003a1c80, 0xc000095200, 0x4, 0x3815329, 0xcd7)
	/home/travis/gopath/src/gocloud.dev/internal/docstore/docstore.go:334 +0x1b9
gocloud.dev/internal/docstore.(*ActionList).toDriverActions(0xc0002d1cd8, 0x1, 0xc000000004, 0x203000, 0x1, 0x0)
	/home/travis/gopath/src/gocloud.dev/internal/docstore/docstore.go:303 +0x1e1
gocloud.dev/internal/docstore.(*ActionList).Do(0xc0002d1cd8, 0x2801880, 0xc0000be010, 0x0, 0x0)
	/home/travis/gopath/src/gocloud.dev/internal/docstore/docstore.go:275 +0x69
gocloud.dev/internal/docstore.(*Collection).Get(0xc0003a1c80, 0x2801880, 0xc0000be010, 0x1ebb680, 0xc00039e060, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/travis/gopath/src/gocloud.dev/internal/docstore/docstore.go:503 +0x11e
gocloud.dev/internal/docstore/drivertest.testCreate.func2(0xc0001446c0)
	/home/travis/gopath/src/gocloud.dev/internal/docstore/drivertest/drivertest.go:237 +0x28e
gocloud.dev/internal/docstore/drivertest.testCreate(0xc00012c400, 0xc0003a1c80)
	/home/travis/gopath/src/gocloud.dev/internal/docstore/drivertest/drivertest.go:246 +0x305
gocloud.dev/internal/docstore/drivertest.withCollection(0xc00012c400, 0xc00005a170, 0x21dbc10)
	/home/travis/gopath/src/gocloud.dev/internal/docstore/drivertest/drivertest.go:192 +0x1f1
gocloud.dev/internal/docstore/drivertest.RunConformanceTests.func3(0xc00012c400)
	/home/travis/gopath/src/gocloud.dev/internal/docstore/drivertest/drivertest.go:148 +0x7a
testing.tRunner(0xc00012c400, 0xc00005a720)
	/home/travis/.gimme/versions/go1.12.5.linux.amd64/src/testing/testing.go:865 +0x164
created by testing.(*T).Run
	/home/travis/.gimme/versions/go1.12.5.linux.amd64/src/testing/testing.go:916 +0x65b
FAIL	gocloud.dev/internal/docstore/mongodocstore	0.134s

```

**Comment by jba** [comment]
Fixed by #2250.
