### ISSUE TITLE
internal/cmd/gocdk: serve crashes immediately

### ISSUE THREAD

**Issue by zombiezen** [google/go-cloud#2607]
@vangent Yup, I'm still filing issues. 🙂

### Describe the bug

Running `gocdk serve` crashes during `biome apply` due to a nil pointer panic.

### To Reproduce

`gocdk serve`

### Expected behavior

A server should be running.

### Actual behavior

```
gocdk: Preparing to serve dev...
gocdk: Checking to see if resource changes are needed...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x2 pc=0xcbcaf0]

goroutine 12 [running]:
main.doBiomeApplyOrDestroy(0x11bb640, 0xc000035880, 0xc0002df260, 0xfd049c, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/light/pkg/mod/gocloud.dev/internal/cmd/gocdk@v0.0.0-20190724210842-d2cfe8b44225/biome.go:329 +0x240
main.biomeApply(0x11bb640, 0xc000035880, 0xc0002df260, 0xfd049c, 0x3, 0x0, 0x0, 0x0)
        /home/light/pkg/mod/gocloud.dev/internal/cmd/gocdk@v0.0.0-20190724210842-d2cfe8b44225/biome.go:273 +0x86
main.serveBuildLoop(0x11bb640, 0xc000035880, 0xc0002df260, 0xc0000cb6d0, 0xc00031a930, 0xc0000355c0, 0x0, 0x0)
        /home/light/pkg/mod/gocloud.dev/internal/cmd/gocdk@v0.0.0-20190724210842-d2cfe8b44225/serve.go:144 +0x2f0
main.serve.func2(0x8, 0x100f660)
        /home/light/pkg/mod/gocloud.dev/internal/cmd/gocdk@v0.0.0-20190724210842-d2cfe8b44225/serve.go:96 +0x57
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc00031a990, 0xc00031a9f0)
        /home/light/pkg/mod/golang.org/x/sync@v0.0.0-20190423024810-112230192c58/errgroup/errgroup.go:57 +0x57
created by golang.org/x/sync/errgroup.(*Group).Go
        /home/light/pkg/mod/golang.org/x/sync@v0.0.0-20190423024810-112230192c58/errgroup/errgroup.go:54 +0x66
```

### Version

gocdk CLI built at d2cfe8b442254eaedc43ce1060b65846b91f3598

### Additional context

The issue appears to be that `gocdk serve` calls `biomeApply` with `nil` options:

https://github.com/google/go-cloud/blob/d2cfe8b442254eaedc43ce1060b65846b91f3598/internal/cmd/gocdk/serve.go#L144

and that when building the Terraform arguments, `doBiomeApplyOrDestroy` does not check for `nil` before dereferencing the options:

https://github.com/google/go-cloud/blob/d2cfe8b442254eaedc43ce1060b65846b91f3598/internal/cmd/gocdk/biome.go#L329

**Comment by zombiezen** [comment]
I'll have a fix sent along shortly.
