### ISSUE TITLE
blob/blob: Panic when using blob.Writer with buffer.WriteTo()

### ISSUE THREAD

**Issue by richardartoul** [google/go-cloud#2750]
### Describe the bug

Some of the code paths in the blob writer `Write()` method return a value of `n` (bytes written) that is larger than the input byte slices length. This is generally considered bad practice for transforming writers and causes panics when trying to copy into the `blob.Writer` from a `bytes.Buffer` using `io.Copy` because the `blob.Writer` indicates that it wrote more bytes than it should have:

```
panic: bytes.Buffer.WriteTo: invalid Write count [recovered]
	panic: bytes.Buffer.WriteTo: invalid Write count

goroutine 21 [running]:
testing.tRunner.func1(0xc000428100)
	/usr/local/Cellar/go/1.13.6/libexec/src/testing/testing.go:874 +0x3a3
panic(0x47eb440, 0x4a90ad0)
	/usr/local/Cellar/go/1.13.6/libexec/src/runtime/panic.go:679 +0x1b2
bytes.(*Buffer).WriteTo(0xc00041a990, 0x566e518, 0xc000291900, 0x566e588, 0xc00041a990, 0xc0002ea901)
	/usr/local/Cellar/go/1.13.6/libexec/src/bytes/buffer.go:241 +0x145
io.copyBuffer(0x566e518, 0xc000291900, 0x4aaa980, 0xc00041a990, 0xc00042e000, 0x8000, 0x8000, 0x48821e0, 0x0, 0x566e518)
	/usr/local/Cellar/go/1.13.6/libexec/src/io/io.go:384 +0x33f
io.CopyBuffer(0x566e518, 0xc000291900, 0x4aaa980, 0xc00041a990, 0xc00042e000, 0x8000, 0x8000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.13.6/libexec/src/io/io.go:375 +0x82
```

### To Reproduce

Use the `io.Copy` function to copy a large number of bytes from a `bytes.Buffer` into a `blob.Writer`

## Expected behavior

The `blob.Writer` should return `n` (number of bytes written) such that it corresponds to the input bytes, not the output bytes. This is how most transforming writer implementing in Golang work.

### Version

Latest.

### Additional context

N.A

**Comment by richardartoul** [comment]
My apologies I was on an older version, this was fixed in: https://github.com/google/go-cloud/commit/61f50f52589b143e7ebc693d8a941ca4802dc29a
