### ISSUE TITLE
pubsub: panic in TestConcurrentReceivesGetAllTheMessages

### ISSUE THREAD

**Issue by vangent** [google/go-cloud#810]
Travis reported this:

```
panic: Fail in goroutine after TestConcurrentReceivesGetAllTheMessages has completed
goroutine 2168 [running]:
testing.(*common).Fail(0xc000575a00)
	/home/travis/.gimme/versions/go1.11.2.linux.amd64/src/testing/testing.go:546 +0x1c6
testing.(*common).FailNow(0xc000575a00)
	/home/travis/.gimme/versions/go1.11.2.linux.amd64/src/testing/testing.go:568 +0x39
testing.(*common).Fatal(0xc000575a00, 0xc000589f88, 0x1, 0x1)
	/home/travis/.gimme/versions/go1.11.2.linux.amd64/src/testing/testing.go:628 +0x7d
github.com/google/go-cloud/internal/pubsub_test.TestConcurrentReceivesGetAllTheMessages.func1(0xc0003e7c20, 0x175d540, 0xc000572a00, 0xc000575a00, 0xc0000ad5d8, 0xc00055bf50, 0xc0000ad5f0)
	/home/travis/gopath/src/github.com/google/go-cloud/internal/pubsub/pubsub_test.go:152 +0x258
created by github.com/google/go-cloud/internal/pubsub_test.TestConcurrentReceivesGetAllTheMessages
```

**Comment by ijt** [comment]
This is not reproducing for me locally. 
```
cd ~/src/github.com/google/go-cloud/internal/pubsub
for i in $(seq 100); do go test -count=1 -run TestConcurrentReceivesGetAllTheMessages; done
```
All 100 runs passed.

**Comment by vangent** [comment]
It's rare but it happens. I just reproduced on master:

```
$ go test -count=1000 -run TestConcurrentReceivesGetAllTheMessages
panic: Fail in goroutine after TestConcurrentReceivesGetAllTheMessages has completed

goroutine 303736 [running]:
testing.(*common).Fail(0xc0003d2100)
	/usr/lib/google-golang/src/testing/testing.go:546 +0x135
testing.(*common).FailNow(0xc0003d2100)
	/usr/lib/google-golang/src/testing/testing.go:568 +0x2b
testing.(*common).Fatal(0xc0003d2100, 0xc0003aff88, 0x1, 0x1)
	/usr/lib/google-golang/src/testing/testing.go:628 +0x6f
github.com/google/go-cloud/internal/pubsub_test.TestConcurrentReceivesGetAllTheMessages.func1(0xc000394050, 0xa35a40, 0xc000376d00, 0xc0003d2100, 0xc000167118, 0xc0001f9b60, 0xc000167150)
	/usr/local/google/home/rvangent/go/src/github.com/google/go-cloud/internal/pubsub/pubsub_test.go:152 +0x179
created by github.com/google/go-cloud/internal/pubsub_test.TestConcurrentReceivesGetAllTheMessages
	/usr/local/google/home/rvangent/go/src/github.com/google/go-cloud/internal/pubsub/pubsub_test.go:145 +0x255
panic: Fail in goroutine after TestConcurrentReceivesGetAllTheMessages has completed

goroutine 303734 [running]:
testing.(*common).Fail(0xc0003d2100)
	/usr/lib/google-golang/src/testing/testing.go:546 +0x135
testing.(*common).FailNow(0xc0003d2100)
	/usr/lib/google-golang/src/testing/testing.go:568 +0x2b
testing.(*common).Fatal(0xc0003d2100, 0xc0003abf88, 0x1, 0x1)
	/usr/lib/google-golang/src/testing/testing.go:628 +0x6f
github.com/google/go-cloud/internal/pubsub_test.TestConcurrentReceivesGetAllTheMessages.func1(0xc000394050, 0xa35a40, 0xc000376d00, 0xc0003d2100, 0xc000167118, 0xc0001f9b60, 0xc000167150)
	/usr/local/google/home/rvangent/go/src/github.com/google/go-cloud/internal/pubsub/pubsub_test.go:152 +0x179
created by github.com/google/go-cloud/internal/pubsub_test.TestConcurrentReceivesGetAllTheMessages
	/usr/local/google/home/rvangent/go/src/github.com/google/go-cloud/internal/pubsub/pubsub_test.go:145 +0x255
exit status 2
FAIL	github.com/google/go-cloud/internal/pubsub	7.944s
```

**Comment by vangent** [comment]
"What this means is that one of the tests called t.Error or t.Fatal some time after the Test function had returned."

**Comment by ijt** [comment]
I tried `go test -count=1000 -run TestConcurrentReceivesGetAllTheMessages` but it timed out.

I got roughly the same panic by adding
```
                cancel()
                t.Fatal("beep boop")
```
right below `topic.Send`:
```
--- FAIL: TestConcurrentReceivesGetAllTheMessages (0.00s)
    pubsub_test.go:174: beep boop
    pubsub_test.go:152: pubsub: Subscription closed
panic: Fail in goroutine after TestConcurrentReceivesGetAllTheMessages has completed
...
```
The `t.Fatal` call causes the deferred call to `s.Close()` to run. The receiving goroutines then get a "Subscription closed" error and call `t.Fatal` on that, in a race with the end of the test. So the solution is probably something like `defer wg.Wait()`.
